name: Publish Nuget package

on:
  release:
    types: [ published ]

jobs:
  build-test-pack:

    runs-on: windows-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        
      - name: Setup MSBuild Path
        uses: microsoft/setup-msbuild@v1.1
        
      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: |
            7.0.x
      - name: Restore dependencies
        run: dotnet restore
        
      - name: Build
        run: msbuild .\Hangfire.Atoms.sln /t:Build /p:Configuration=Release

      - name: Pack
        run: dotnet pack ./src/Hangfire.Atoms/Hangfire.Atoms.csproj --output nupkgs --no-build --configuration Release -p:PackageVersion=${{ github.event.release.tag_name }}

      - name: Push
        run: dotnet nuget push ./nupkgs/Hangfire.Atoms.${{ github.event.release.tag_name }}.nupkg --source https://api.nuget.org/v3/index.json --api-key ${{ secrets.NUGET_API_KEY }}
      
